---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
    opa-istio-injection: enabled
  name: demo-test-1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-service-account
  namespace: demo-test-1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-test-1-app-1-service-account
  namespace: demo-test-1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-test-1-app-2-service-account
  namespace: demo-test-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    microservice: demo-test-1-app-1
    version: 2.2.7.41
  name: demo-test-1-app-1-0000-deployment
  namespace: demo-test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-test-1-app-1-0000
  template:
    metadata:
      labels:
        app: demo-test-1-app-1-0000
        microservice: demo-test-1-app-1
    spec:
      containers:
      - env:
        - name: DEPLOY_ENV
          value: INT
        - name: PORT
          value: "8080"
        - name: VCAP_APPLICATION
          value: '{}'
        - name: DISABLE_CONFIG_AGENT
          value: 'true'
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: demo-test-1-app-1-0000
        ports:
        - containerPort: 80
          name: http-default
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128M
          requests:
            cpu: 50m
            memory: 128M
      imagePullSecrets:
      - name: cms-acr-pull-secret
      serviceAccount: demo-test-1-app-1-service-account
      serviceAccountName: demo-test-1-app-1-service-account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    microservice: demo-test-1-app-2
    version: 2.2.7.41
  name: demo-test-1-app-2-0000-deployment
  namespace: demo-test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-test-1-app-2-0000
  template:
    metadata:
      labels:
        app: demo-test-1-app-2-0000
        microservice: demo-test-1-app-2
    spec:
      containers:
      - env:
        - name: DEPLOY_ENV
          value: INT
        - name: PORT
          value: "8080"
        - name: VCAP_APPLICATION
          value: '{}'
        - name: DISABLE_CONFIG_AGENT
          value: 'true'
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: demo-test-1-app-2-0000
        ports:
        - containerPort: 80
          name: http-default
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128M
          requests:
            cpu: 50m
            memory: 128M
      imagePullSecrets:
      - name: cms-acr-pull-secret
      serviceAccount: demo-test-1-app-2-service-account
      serviceAccountName: demo-test-1-app-2-service-account
---
apiVersion: v1
kind: Service
metadata:
  labels:
    microservice: demo-test-1-app-1
  name: demo-test-1-app-1-0000-service
  namespace: demo-test-1
spec:
  ports:
  - name: http-default
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-test-1-app-1-0000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    microservice: demo-test-1-app-1
  name: demo-test-1-app-1-service
  namespace: demo-test-1
spec:
  ports:
  - name: http-default
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-test-1-app-1-0000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    microservice: demo-test-1-app-2
  name: demo-test-1-app-2-0000-service
  namespace: demo-test-1
spec:
  ports:
  - name: http-default
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-test-1-app-2-0000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    microservice: demo-test-1-app-2
  name: demo-test-1-app-2-service
  namespace: demo-test-1
spec:
  ports:
  - name: http-default
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-test-1-app-2-0000
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    microservice: demo-test-1-app-1
  name: demo-test-1-app-1-0000-virtualservice
  namespace: demo-test-1
spec:
  gateways:
  - istio-system/http-gateway
  - istio-system/https-gateway
  hosts:
  - demo-test-1-app-1.sst.suse.lab
  http:
  - headers:
      request:
        set:
          x-forwarded-port: "443"
          x-forwarded-proto: https
    route:
    - destination:
        host: demo-test-1-app-1-0000-service.demo-test-1.svc.cluster.local
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    microservice: demo-test-1-app-2
  name: demo-test-1-app-2-0000-virtualservice
  namespace: demo-test-1
spec:
  gateways:
  - mesh
  hosts:
  - demo-test-1-app-2.sst.suse.lab
  http:
  - headers:
      request:
        set:
          x-forwarded-port: "443"
          x-forwarded-proto: https
    route:
    - destination:
        host: demo-test-1-app-2-0000-service.demo-test-1.svc.cluster.local
        port:
          number: 8080
